#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use Grahl\OFReader\getTasks;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new getTasks());
$application->run();